services:
  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: "local"

  mjpeg_streamer:
    container_name: mjpeg_streamer
    image: edgeeye_mjpeg_streamer
    build:
      context: .
      dockerfile: Dockerfile-streamer
    restart: always
    logging:
      driver: "local"
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ:-UTC}
      - LANG=${LANG:-en_US.UTF-8}
    command: npm start -- -r ${REDIS_URL:-redis://redis}

  edgeeye_reassembler:
    container_name: edgeeye_reassembler
    image: edgeeye_reassembler
    build:
      context: .
      dockerfile: Dockerfile-reassembler
    restart: always
    logging:
      driver: "local"
    environment:
      - TZ=${TZ:-UTC}
      - LANG=${LANG:-en_US.UTF-8}
    command:
      - python3
      - -u
      - EdgeEye.py
      - --mqtt_url
      - ${MQTT_URL:-tcp://mosquitto:1883}
      - --redis_url
      - ${REDIS_URL:-redis://redis}
      - --device_profile_id
      - ${DEVICE_PROFILE_ID}
