FROM python:3-alpine
WORKDIR /root/

RUN apk add --no-cache nodejs
RUN python3 -m pip install redis
RUN python3 -m pip install pillow
RUN python3 -m pip install numpy
RUN python3 -m pip install pyjwt
RUN python3 -m pip install paho-mqtt
RUN python3 -m pip install aiohttp

COPY ./post-processor .

# Default environment variables (can be overridden)
ENV MQTT_URL="mqtt://localhost:1883"
ENV REDIS_URL="redis://localhost:6379"
ENV DEVICE_PROFILE_ID=""

CMD [ "python3", "-u", "EdgeEye.py", "--mqtt_url", "$MQTT_URL", "--redis_url", "$REDIS_URL", "--device_profile_id", "$DEVICE_PROFILE_ID" ]
